global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafkastarter'
    metrics_path: /kafkastarter/actuator/prometheus
    static_configs:
      - targets:
          - kafkastarter:8080